import { chromium } from 'playwright-core';
const CHROME = '/home/judah/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome';
const ADMIN = 'http://127.0.0.1:3011';
const browser = await chromium.launch({ executablePath: CHROME, headless: false });
const page = await browser.newPage();
page.on('console', msg => console.log('BROWSER:', msg.type(), msg.text()));
page.on('pageerror', e => console.log('PAGE ERROR:', e.message));
await page.goto(ADMIN + '/login', { waitUntil: 'networkidle' });
await page.fill('#email', 'admin@e2e.test');
await page.fill('#password', 'senha12345');
await page.fill('#tenant', 'default');
await page.click('#login-form button[type="submit"]');
await page.waitForURL(ADMIN + '/');
await page.goto(ADMIN + '/users/new', { waitUntil: 'networkidle' });
await page.waitForSelector('label:has-text("Nome") input');
console.log('--- form loaded, checking select ---');
const select = await page.$('select');
const opts = await select.$$eval('option', els => els.map(e => e.textContent));
console.log('options:', opts);
await browser.close();
