// @oktis-works/cms - Assets canônicos de deploy embutidos na CLI
//
// Um projeto gerado pelo `okcms init` não tem (e não pode ter) acesso a este
// repositório — então os arquivos de infraestrutura viajam DENTRO do pacote
// npm como strings e são escritos em disco pelo scaffold/update.
//
// Estes textos são a fonte canônica. `infrastructure/**` espelha cada um deles
// e o teste `assets.test.ts` falha se divergirem: sem isso a cópia em
// infraestrutura vira documentação morta que ninguém atualiza.
//
// Escapamento: dentro dos template literals todo `${...}` do shell/compose
// precisa virar `\${...}` para não virar interpolação do TypeScript.

/** Espelhos em disco (mantidos em sincronia por teste). */
export const ASSET_MIRROR = {
  dockerfile: 'infrastructure/docker/Dockerfile',
  entrypoint: 'infrastructure/docker/entrypoint.sh',
  dockerignore: 'infrastructure/docker/.dockerignore',
  composeInfra: 'infrastructure/compose/docker-compose.infra.yml',
  composeDeploy: 'infrastructure/compose/docker-compose.deploy.yml',
  nginxTemplate: 'infrastructure/nginx/templates/default.conf.template',
} as const;

// ---------------------------------------------------------------------------
// Imagem única — 4 entrypoints (api | admin | web | worker)
// ---------------------------------------------------------------------------

/**
 * Uma imagem para os quatro papéis: mesma camada de dependências em cache,
 * processo escolhido pelo `command` do compose. Quatro Dockerfiles seriam
 * quatro builds idênticos consumindo o mesmo node_modules.
 */
export const DOCKERFILE = `# syntax=docker/dockerfile:1
# @oktis-works - Single OkCMS image (entrypoints: api | admin | web | worker)
#
# Generated by the CLI scaffold. Canonical at
# infrastructure/docker/Dockerfile in this monorepo.
#
# SECURITY: the command-line tool never enters this image. The container
# exposes only the application processes — no package installer, no Docker
# socket access, no way to change its own state. Deploy and configuration
# always run on the host.
FROM oven/bun:1-alpine AS base
WORKDIR /app
ENV NODE_ENV=production
ENV UPLOAD_DIR=/app/.data/storage

# --- dependencies -----------------------------------------------------------
# Manifest + lock first: changing just the code does not invalidate
# this \`install\`.
FROM base AS deps
COPY package.json bun.lock* package-lock.json* yarn.lock* pnpm-lock.yaml* ./
RUN bun install --production --frozen-lockfile

# --- runtime ----------------------------------------------------------------
FROM base AS runtime
# 1. project code (.dockerignore drops .env, node_modules and .data)
COPY . .
# 2. clean node_modules from the deps stage, on top — never the host's
COPY --from=deps /app/node_modules ./node_modules

RUN mkdir -p /app/.data/storage /app/.data/cache /app/logs

EXPOSE 3000 3001 3011

# \`docker compose ... command: api\` picks the role; see docker/entrypoint.sh
ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["api"]
`;

/** Dispatcher de papéis. Fora da lista, executa o comando literal. */
export const ENTRYPOINT_SH = `#!/bin/sh
# @oktis-works - Single entrypoint of the okcms/app image
#
# Compose picks the role with \`command: api|web|admin|worker\`. Any other
# value is passed through literally (\`docker run okcms/app sh\`), which keeps
# the container inspectable without rewriting the image.
set -eu

api_entry="node_modules/@oktis-works/api/dist/index.js"
web_entry="node_modules/@oktis-works/web/dist/index.js"
admin_entry="node_modules/@oktis-works/admin/bin/admin.js"
worker_entry="node_modules/@oktis-works/worker/dist/index.js"

case "\${1:-api}" in
  api)
    shift
    exec bun "$api_entry" "$@"
    ;;
  web)
    shift
    exec bun "$web_entry" "$@"
    ;;
  admin)
    shift
    exec bun "$admin_entry" "$@"
    ;;
  worker)
    shift
    exec bun "$worker_entry" "$@"
    ;;
  *)
    exec "$@"
    ;;
esac
`;

/**
 * Camada de segurança do build: além do ganho de cache, impede dois acidentes
 * caros — assinar a imagem com o `.env` real e instalar `node_modules` do host
 * (arquitetura diferente / código não auditado).
 */
export const DOCKERIGNORE = `# @oktis-works - build context of the okcms/app image
# .env NEVER enters the image: it carries the database password and
# JWT_SECRET, and the image is distributed/copied. At runtime it comes
# from the host via env_file.

.env
.env.*
!.env.example

# host dependencies (the image installs its own)
node_modules
**/node_modules
.tsbuildinfo
**/*.tsbuildinfo
# NB: do NOT ignore dist/ — plugins installed in plugins/*/dist are runtime.

# local data and state
.data
**/.data
logs
**/logs
*.log
coverage
**/coverage

# mounted at runtime, not copied
deploy/

# VCS and tooling — not runtime code
.git
.github
.gitignore
.sdd
.vscode
.idea
.claude
*.md
!README.md

# Source code & tests (not needed in runtime image)
*.ts
*.tsx
*.test.*
*.spec.*
test/
tests/
spec/
__tests__/
__mocks__/

# Docs & tooling
scripts/
docs/

# Maps & build artifacts
*.map
tsconfig*.json
.turbo/
.cache/

# infrastructure mounted at runtime, not copied inside
docker-compose*.yml
deploy/nginx/certs
`;

// ---------------------------------------------------------------------------
// Infra compartilhada (projeto Docker `okcms`)
// ---------------------------------------------------------------------------

/**
 * Banco, cache e proxy — únicos e estáveis por toda a vida do site. Moram num
 * projeto PRÓPRIO para que `docker compose -p okcms-blue down` não derrube o
 * banco junto com a lane antiga.
 */
export const COMPOSE_INFRA = `# @oktis-works - Shared infrastructure of the production deploy
# Generated by the CLI. Canonical at
# infrastructure/compose/docker-compose.infra.yml
#
# OWN Docker project (okcms): single postgres, redis and proxy. The
# blue/green lanes are separate projects (okcms-blue / okcms-green) that
# join this network as external — so \`down\` of a lane never touches the
# database.
#
#   docker compose -p okcms -f docker-compose.infra.yml up -d
name: okcms

services:
  postgres:
    image: postgres:16-alpine
    container_name: okcms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: \${DB_NAME:-okcms}
      POSTGRES_USER: \${DB_USER:-postgres}
      POSTGRES_PASSWORD: \${DB_PASSWORD:?set DB_PASSWORD in .env}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      # Loopback only: the host can run \`okcms db:migrate\` and
      # \`db:backup\` without exposing Postgres to the network. On managed
      # production remove this block and point DB_HOST/DATABASE_URL at the
      # provider.
      - "127.0.0.1:\${DB_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $\${POSTGRES_USER} -d $\${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    labels:
      # classification read by \`okcms update\`: data = untouchable
      okcms.role: data
    networks: [okcms]

  redis:
    image: redis:7-alpine
    container_name: okcms-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: \${REDIS_PASSWORD:-}
    command:
      - sh
      - -c
      - |
        if [ -n "$\${REDIS_PASSWORD:-}" ]; then
          exec redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"
        else
          exec redis-server --appendonly yes
        fi
    # no published port: only what is on okcms-net can reach Redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    labels:
      okcms.role: data
    networks: [okcms]

  proxy:
    image: nginx:1.27-alpine
    container_name: okcms-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      # fed to the native nginx envsubst → writes conf.d/default.conf
      SERVER_NAME: \${SERVER_NAME:-_}
      ADMIN_SERVER_NAME: \${ADMIN_SERVER_NAME:-admin.localhost}
    volumes:
      - ./deploy/nginx/templates:/etc/nginx/templates:ro
      # conf.d must be writable: the CLI rewrites 00-upstreams.conf on swap
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:rw
    labels:
      okcms.role: proxy
    networks: [okcms]

networks:
  okcms:
    # fixed name — the lanes declare it as external
    name: okcms-net

volumes:
  postgres-data:
    name: okcms-postgres-data
  redis-data:
    name: okcms-redis-data
`;

// ---------------------------------------------------------------------------
// Lanes blue/green (projetos Docker `okcms-blue` / `okcms-green`)
// ---------------------------------------------------------------------------

/**
 * Um arquivo, dois projetos Docker. O "lane" é o NOME DO PROJETO — não há
 * serviço repetido por perfil nem perfil a ativar manualmente; basta
 * `-p okcms-blue` ou `-p okcms-green`. Os containers herdam o prefixo
 * `okcms-<lane>-`, que é exatamente o que os upstreams do nginx apontam.
 */
export const COMPOSE_DEPLOY = `# @oktis-works - OkCMS blue/green lanes
# Generated by the CLI. Canonical at
# infrastructure/compose/docker-compose.deploy.yml
#
# ONE FILE, TWO Docker projects. The lane is the project name:
#
#   docker compose -p okcms-blue  -f docker-compose.deploy.yml up -d --build
#   docker compose -p okcms-green -f docker-compose.deploy.yml up -d --build
#
# Containers are okcms-<lane>-<service> — the nginx upstreams point at
# those names (generated in deploy/nginx/conf.d/00-upstreams.conf).
#
# The okcms-net network is EXTERNAL (created by docker-compose.infra.yml)
# and the infra services are NOT listed here on purpose: without that,
# \`down\` of a lane would take the database down with the old lane.
#
# Roles (label okcms.role, read by \`okcms update\`):
#   edge   api/web/admin → fully replaced on each deploy (blue/green)
#   worker BullMQ queue  → NEVER blue/green; drained with SIGTERM on swap
#   data   postgres/redis→ untouchable; they live in docker-compose.infra.yml
#
# NB: a lane \`down\` removes CONTAINERS and NETWORKS, but never passes -v
# (\`-v\` would wipe the okcms-storage volume shared by blue and green, the
# one that keeps media alive across deploys).

x-app: &app
  image: okcms/app:\${OKCMS_VERSION:-latest}
  build:
    context: .
    dockerfile: docker/Dockerfile
  env_file:
    # .env first (operator ports) — the environment below overrides
    - .env
  restart: unless-stopped
  networks: [okcms]
  environment:
    NODE_ENV: production
    DB_HOST: postgres
    REDIS_HOST: redis
    UPLOAD_DIR: /app/.data/storage
  volumes:
    - ./plugins:/app/plugins
    - ./themes:/app/themes
    # media shared by both lanes: a deploy never loses files
    - storage-data:/app/.data/storage
    - cache-data:/app/.data/cache

x-api-health: &api-health
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 25s

x-web-health: &web-health
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.WEB_PORT||3001)+'/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 25s

x-admin-health: &admin-health
  # the admin is an Astro standalone: it serves / and has no /health endpoint
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.PORT||3011)+'/').then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 30s

services:
  # ---------------------------------------------------------------- api
  api-blue:
    <<: *app
    container_name: okcms-api-blue
    command: ["api"]
    labels:
      okcms.role: edge
      okcms.lane: blue
      okcms.service: api
    healthcheck: *api-health

  api-green:
    <<: *app
    container_name: okcms-api-green
    command: ["api"]
    labels:
      okcms.role: edge
      okcms.lane: green
      okcms.service: api
    healthcheck: *api-health

  # ---------------------------------------------------------------- web
  web-blue:
    <<: *app
    container_name: okcms-web-blue
    command: ["web"]
    labels:
      okcms.role: edge
      okcms.lane: blue
      okcms.service: web
    healthcheck: *web-health

  web-green:
    <<: *app
    container_name: okcms-web-green
    command: ["web"]
    labels:
      okcms.role: edge
      okcms.lane: green
      okcms.service: web
    healthcheck: *web-health

  # -------------------------------------------------------------- admin
  # admin reads \`PORT\` (astro standalone), not \`ADMIN_PORT\`: a service
  # level environment replaces the merged anchor one, so the three shared
  # ones are repeated.
  admin-blue:
    <<: *app
    container_name: okcms-admin-blue
    command: ["admin"]
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      REDIS_HOST: redis
      PORT: \${ADMIN_PORT:-3011}
      UPLOAD_DIR: /app/.data/storage
    labels:
      okcms.role: edge
      okcms.lane: blue
      okcms.service: admin
    healthcheck: *admin-health

  admin-green:
    <<: *app
    container_name: okcms-admin-green
    command: ["admin"]
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      REDIS_HOST: redis
      PORT: \${ADMIN_PORT:-3011}
      UPLOAD_DIR: /app/.data/storage
    labels:
      okcms.role: edge
      okcms.lane: green
      okcms.service: admin
    healthcheck: *admin-health

  # ------------------------------------------------------------- worker
  # a queue cannot take two "ghost" instances: the worker starts only after
  # the swap and the old lane's worker drains with SIGTERM
  # (stop_grace_period) first.
  worker-blue:
    <<: *app
    container_name: okcms-worker-blue
    command: ["worker"]
    stop_grace_period: 30s
    labels:
      okcms.role: worker
      okcms.lane: blue
      okcms.service: worker

  worker-green:
    <<: *app
    container_name: okcms-worker-green
    command: ["worker"]
    stop_grace_period: 30s
    labels:
      okcms.role: worker
      okcms.lane: green
      okcms.service: worker

networks:
  okcms:
    name: okcms-net
    external: true

volumes:
  # shared between blue and green on purpose: media survives the deploy
  storage-data:
    name: okcms-storage
  cache-data:
    name: okcms-cache
`;

// ---------------------------------------------------------------------------
// Simple container stack (docker-compose.app.yml) — one project, no lanes
// ---------------------------------------------------------------------------

/**
 * The non-blue/green path: one Docker project (`okcms-app`) holding api, web,
 * admin and worker without lane suffixes. `up -d --build` recreates only what
 * changed, there is no second lane to keep warm and no proxy swap — the nginx
 * upstreams simply point at `okcms-api` / `okcms-web` / `okcms-admin`.
 *
 * Network and volumes are the same ones the lanes use, so storage (media)
 * survives a switch between simple mode and blue/green.
 */
export const COMPOSE_APP = `# @oktis-works - Simple container stack of OkCMS
# Generated by the CLI.
#
# One Docker project, no lanes, no swap:
#
#   docker compose -p okcms-app -f docker-compose.app.yml up -d --build
#
# Containers are okcms-api / okcms-web / okcms-admin / okcms-worker — the
# nginx upstreams (deploy/nginx/conf.d/00-upstreams.conf) point at them.
# Use \`okcms deploy\` to pick this mode, or blue/green for zero-downtime.
#
# Network okcms-net is EXTERNAL (created by docker-compose.infra.yml), so
# \`down\` of this stack never touches postgres, redis or the proxy.

x-app: &app
  image: okcms/app:\${OKCMS_VERSION:-latest}
  build:
    context: .
    dockerfile: docker/Dockerfile
  env_file:
    - .env
  restart: unless-stopped
  networks: [okcms]
  environment:
    NODE_ENV: production
    DB_HOST: postgres
    REDIS_HOST: redis
  volumes:
    - ./plugins:/app/plugins
    - ./themes:/app/themes
    - storage-data:/app/.data/storage
    - cache-data:/app/.data/cache

x-api-health: &api-health
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 25s

x-web-health: &web-health
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.WEB_PORT||3001)+'/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 25s

x-admin-health: &admin-health
  # the admin is an Astro standalone: it serves / and has no /health endpoint
  test:
    - CMD
    - bun
    - -e
    - "fetch('http://127.0.0.1:'+(process.env.PORT||3011)+'/').then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"
  interval: 10s
  timeout: 5s
  retries: 12
  start_period: 30s

services:
  api:
    <<: *app
    container_name: okcms-api
    command: ["api"]
    labels:
      okcms.role: edge
      okcms.service: api
    healthcheck: *api-health

  web:
    <<: *app
    container_name: okcms-web
    command: ["web"]
    labels:
      okcms.role: edge
      okcms.service: web
    healthcheck: *web-health

  # the admin reads \`PORT\` (astro standalone), not \`ADMIN_PORT\`: a service
  # level environment replaces the merged anchor one, so it is repeated here.
  admin:
    <<: *app
    container_name: okcms-admin
    command: ["admin"]
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      REDIS_HOST: redis
      PORT: \${ADMIN_PORT:-3011}
      UPLOAD_DIR: /app/.data/storage
    labels:
      okcms.role: edge
      okcms.service: admin
    healthcheck: *admin-health

  worker:
    <<: *app
    container_name: okcms-worker
    command: ["worker"]
    stop_grace_period: 30s
    labels:
      okcms.role: worker
      okcms.service: worker

networks:
  okcms:
    name: okcms-net
    external: true

volumes:
  # same names as the lanes: media survives switching deploy modes
  storage-data:
    name: okcms-storage
  cache-data:
    name: okcms-cache
`;

// ---------------------------------------------------------------------------
// Proxy nginx (projeto do operador: deploy/nginx/)
// ---------------------------------------------------------------------------

/**
 * Roteamento production. Os upstreams ficam em arquivo SEPARADO
 * (`00-upstreams.conf`) justamente para que o swap seja uma reescrita de um
 * arquivo minúsculo + `nginx -s reload` — sem tocar no `server` block e sem
 * reiniciar o container.
 *
 * `SERVER_NAME` / `ADMIN_SERVER_NAME` entram pelo envsubst nativo do nginx;
 * as variáveis em `$host`/`$upstream_*` são do nginx e ficam intactas porque
 * o envsubst só substitui a lista de variáveis definidas no ambiente.
 */
export const NGINX_TEMPLATE = `# @oktis-works - OkCMS proxy routing (template)
# Generated by the CLI. Canonical at
# infrastructure/nginx/templates/default.conf.template
#
# The official nginx image runs /etc/nginx/templates/*.template on start,
# with envsubst limited to the variables defined in the environment
# (SERVER_NAME and ADMIN_SERVER_NAME, coming from the .env). Anything that
# is \$host, \$remote_addr or \$upstream_* belongs to nginx and is NOT
# substituted.
#
# The upstreams live in conf.d/00-upstreams.conf: the CLI rewrites them on
# swap and reloads with \`nginx -s reload\` — lane switch without dropping
# connections.

map \$http_upgrade \$connection_upgrade {
  default upgrade;
  ''      close;
}

# ---------------------------------------------------------------- admin ----
# The admin is an Astro standalone served at the ROOT (not /admin): it emits
# /_astro/... URLs and has no configured base path, so publishing it under
# /admin/ would break the assets. It needs its own host.
server {
  listen 80;
  server_name \${ADMIN_SERVER_NAME};

  # API proxy for admin (cookies + CSRF need same-origin or explicit proxy)
  location /api/ {
    proxy_pass \$upstream_api;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
    # Cookies from API must be passed through to browser
    proxy_hide_header Set-Cookie;
    proxy_set_header Cookie \$http_cookie;
  }

  location / {
    proxy_pass \$upstream_admin;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
  }
}

# admin by port — works without any DNS (http://<host>:8080/)
server {
  listen 8080 default_server;
  server_name _;

  # API proxy for admin (cookies + CSRF need same-origin or explicit proxy)
  location /api/ {
    proxy_pass \$upstream_api;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
    # Cookies from API must be passed through to browser
    proxy_hide_header Set-Cookie;
    proxy_set_header Cookie \$http_cookie;
  }

  location / {
    proxy_pass \$upstream_admin;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
  }
}

# ----------------------------------------------------------- public site ---
server {
  listen 80 default_server;
  server_name \${SERVER_NAME};

  client_max_body_size 100m;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript
             image/svg+xml;

  # edge healthcheck: always on the api (it is the one talking to the database)
  location = /health {
    access_log off;
    proxy_pass \$upstream_api;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
  }

  # API + media (/api/v1/media/file/<tenant>/<file>)
  location /api/ {
    proxy_pass \$upstream_api;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
  }

  # STORAGE_PUBLIC_BASE=/storage → routes the same file to the API.
  # The local driver publishes <base>/<tenant>/<file>, which is exactly the
  # format of /api/v1/media/file/<tenant>/<file>.
  location /storage/ {
    rewrite ^/storage/(.*)\$ /api/v1/media/file/\$1 break;
    proxy_pass \$upstream_api;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_cache_valid 200 30d;
    expires 30d;
  }

  # theme assets served by the web (Theme SDK path resolver)
  location /themes/ {
    proxy_pass \$upstream_web;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }

  # SSR of the public site
  location / {
    proxy_pass \$upstream_web;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_read_timeout 120s;
  }
}
`;

export type Lane = 'blue' | 'green';

export interface UpstreamPorts {
  api: number;
  web: number;
  admin: number;
}

export const DEFAULT_UPSTREAM_PORTS: UpstreamPorts = { api: 3000, web: 3001, admin: 3011 };

/**
 * Conteúdo de `deploy/nginx/conf.d/00-upstreams.conf`.
 *
 * Só a linha de cada `map` muda no swap — é esse o truque do blue/green via
 * arquivo: reescrever 3 linhas é atômico e `nginx -s reload` re-lê sem
 * fechar conexão estabelecida.
 */
export function renderUpstreams(lane: Lane, ports: UpstreamPorts = DEFAULT_UPSTREAM_PORTS): string {
  return `# @oktis-works - Active upstreams (GENERATED by the CLI — do not edit by hand)
#
# Rewritten by \`okcms update\` at swap time and reloaded with
#   docker exec okcms-proxy nginx -s reload
# Points at containers of the Docker project okcms-<lane> on okcms-net.
# Media, cache and database are NOT blue/green — they live in the \`okcms\`
# project.

map \$host \$upstream_api {
  default http://okcms-api-${lane}:${ports.api};
}

map \$host \$upstream_web {
  default http://okcms-web-${lane}:${ports.web};
}

map \$host \$upstream_admin {
  default http://okcms-admin-${lane}:${ports.admin};
}
`;
}

/**
 * Upstreams for the SIMPLE stack (`okcms deploy --target simple`): the same
 * nginx config, pointing at the lane-less containers. Switching modes is a
 * rewrite of this file plus `nginx -s reload`.
 */
export function renderSimpleUpstreams(ports: UpstreamPorts = DEFAULT_UPSTREAM_PORTS): string {
  return `# @oktis-works - Active upstreams (GENERATED by the CLI — do not edit by hand)
#
# Simple mode: one stack only (docker-compose.app.yml), no lanes.
# Rewritten by \`okcms deploy --target simple\` and reloaded with
#   docker exec okcms-proxy nginx -s reload
# Points at the okcms-api / okcms-web / okcms-admin containers on okcms-net.

map \$host \$upstream_api {
  default http://okcms-api:${ports.api};
}

map \$host \$upstream_web {
  default http://okcms-web:${ports.web};
}

map \$host \$upstream_admin {
  default http://okcms-admin:${ports.admin};
}
`;
}

// ---------------------------------------------------------------------------
// Caminhos no projeto do operador + montagem dos assets
// ---------------------------------------------------------------------------

export const DEPLOY_PATHS = {
  dockerignore: '.dockerignore',
  dockerfile: 'docker/Dockerfile',
  entrypoint: 'docker/entrypoint.sh',
  composeInfra: 'docker-compose.infra.yml',
  composeDeploy: 'docker-compose.deploy.yml',
  composeApp: 'docker-compose.app.yml',
  nginxTemplate: 'deploy/nginx/templates/default.conf.template',
  nginxUpstreams: 'deploy/nginx/conf.d/00-upstreams.conf',
} as const;

/** Arquivo gerado pelo envsubst no start do nginx — fica fora do git. */
export const NGINX_GENERATED = 'deploy/nginx/conf.d/default.conf';

/** Entradas de `.gitignore` que evitam commitar artefato gerado. */
export const DEPLOY_GITIGNORE = [
  NGINX_GENERATED,
  'docker-compose.override.yml',
  '.data/',
  // estado de runtime da lane ativa — varia por máquina, conflita em merge
  '.deploy/',
];

export interface ProjectAsset {
  path: string;
  content: string;
  /** permissão no disco — só o entrypoint é executável. */
  mode?: number;
}

/** Lê as portas reais do `.env`, com fallback para os defaults dos apps. */
export function portsFromEnv(record: Record<string, string>): UpstreamPorts {
  const port = (value: string | undefined, fallback: number): number => {
    const parsed = Number(value);
    return Number.isInteger(parsed) && parsed > 0 && parsed <= 65535 ? parsed : fallback;
  };
  return {
    api: port(record['PORT'], DEFAULT_UPSTREAM_PORTS.api),
    web: port(record['WEB_PORT'], DEFAULT_UPSTREAM_PORTS.web),
    admin: port(record['ADMIN_PORT'], DEFAULT_UPSTREAM_PORTS.admin),
  };
}

/**
 * Todos os arquivos de deploy do projeto, prontos para escrita.
 * `lane`/`ports` só definem o upstream INICIAL (lane vazia → blue); depois
 * disso quem reescreve esse arquivo é o `okcms update`, a cada swap.
 *
 * `00-upstreams.conf` é versionado de propósito (sem segredo, aponta para um
 * container que ainda vai existir) — sem ele um clone limpo sobe um nginx
 * sem upstream nenhum. Já `default.conf` é gerado pelo envsubst e fica fora.
 */
export function deployAssets(
  lane: Lane = 'blue',
  ports: UpstreamPorts = DEFAULT_UPSTREAM_PORTS
): ProjectAsset[] {
  return [
    { path: DEPLOY_PATHS.dockerignore, content: DOCKERIGNORE },
    { path: DEPLOY_PATHS.dockerfile, content: DOCKERFILE },
    { path: DEPLOY_PATHS.entrypoint, content: ENTRYPOINT_SH, mode: 0o755 },
    { path: DEPLOY_PATHS.composeInfra, content: COMPOSE_INFRA },
    { path: DEPLOY_PATHS.composeDeploy, content: COMPOSE_DEPLOY },
    { path: DEPLOY_PATHS.composeApp, content: COMPOSE_APP },
    { path: DEPLOY_PATHS.nginxTemplate, content: NGINX_TEMPLATE },
    { path: DEPLOY_PATHS.nginxUpstreams, content: renderUpstreams(lane, ports) },
  ];
}
