// @oktis-works/cms - PM2 deploy target (shared by deploy / update / redeploy)
//
// PM2 runs the four apps as host processes — no Docker image, no lanes. The
// order is the same contract as every other target:
//
//   1. pm2 binary present (installs it on demand)
//   2. ecosystem.config.js exists (generated once, never overwritten)
//   3. packages updated on the host when asked (`--install`)
//   4. db:migrate on the host — before anything is (re)started
//   5. `pm2 startOrReload` — starts a first deploy and reloads the rest
//   6. history entry + project docs refresh
//
// `startOrReload` instead of `reload all`: `reload` fails when the processes
// are not registered yet, which is exactly the first-deploy case.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { migrateInvocation } from './bluegreen.js';
import { defaultRunner, type Runner } from './docker.js';
import type { Prompt } from './prompt.js';
import type { OutdatedEntry } from './update.js';

const PM2_ECOSYSTEM_TEMPLATE = `// ecosystem.config.js — generated by okcms deploy (PM2)
// Edit as needed and run: pm2 reload all

const path = require('node:path');
let storagePath = process.env.STORAGE_LOCAL_PATH || '.data/storage';
try {
  const project = require('./okcms.config.json');
  storagePath = project.storage?.localPath || storagePath;
} catch {
  // The default keeps projects without okcms.config.json working.
}
const uploadDir = path.isAbsolute(storagePath) ? storagePath : path.resolve(__dirname, storagePath);

module.exports = {
  apps: [
    {
      name: 'okcms-api',
      script: 'bunx',
      args: '@oktis-works/api',
      env: { NODE_ENV: 'production', PORT: 3000, UPLOAD_DIR: uploadDir },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'okcms-admin',
      script: 'bunx',
      args: '@oktis-works/admin',
      env: { NODE_ENV: 'production', PORT: 3011, PUBLIC_API_URL: process.env.PUBLIC_API_URL || 'http://localhost:3000' },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'okcms-web',
      script: 'bunx',
      args: '@oktis-works/web',
      env: { NODE_ENV: 'production', WEB_PORT: 3001 },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'okcms-worker',
      script: 'bunx',
      args: '@oktis-works/worker',
      env: { NODE_ENV: 'production', WORKER_MODE: 'pm2', UPLOAD_DIR: uploadDir },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
  ],
};
`;

export interface Pm2DeployOptions {
  cwd?: string;
  prompt: Prompt;
  runner?: Runner;
  /** Packages reported as outdated by the caller (drives install + history). */
  outdated?: OutdatedEntry[];
  /** Update packages on the host as part of this deploy (`--install`). */
  install?: boolean;
  /** Run `db:migrate` before starting (default: true). */
  migrate?: boolean;
  /** `--yes`: no prompts at all. */
  yes?: boolean;
}

/** Is PM2 installed globally? */
async function checkPm2Installed(runner: Runner): Promise<boolean> {
  return runner('pm2', ['--version'], { timeoutMs: 10_000 }).ok;
}

/** Install PM2 globally via bun, falling back to npm. */
async function installPm2(runner: Runner): Promise<boolean> {
  if (runner('bun', ['add', '-g', 'pm2'], { inherit: true, timeoutMs: 120_000 }).ok) return true;
  return runner('npm', ['install', '-g', 'pm2'], { inherit: true, timeoutMs: 120_000 }).ok;
}

/** Writes ecosystem.config.js when missing (never overwrites an edited file). */
function ensureEcosystemConfig(cwd: string): boolean {
  const path = join(cwd, 'ecosystem.config.js');
  if (existsSync(path)) return false;
  writeFileSync(path, PM2_ECOSYSTEM_TEMPLATE, 'utf-8');
  return true;
}

/** Snapshot of package.json so a rollback can restore previous versions. */
function snapshotPackageJson(cwd: string): string | undefined {
  const path = join(cwd, 'package.json');
  return existsSync(path) ? readFileSync(path, 'utf-8') : undefined;
}

export async function deployPm2(opts: Pm2DeployOptions): Promise<number> {
  const cwd = opts.cwd ?? process.cwd();
  const prompt = opts.prompt;
  const runner = opts.runner ?? defaultRunner;
  const outdated = opts.outdated ?? [];

  // ---- 1. pm2 binary ------------------------------------------------------
  if (!(await checkPm2Installed(runner))) {
    prompt.warn('PM2 not found.');
    if (opts.yes !== true) {
      const installIt = await prompt.confirm('Install PM2 globally now? (bun add -g pm2)', {
        defaultValue: true,
      });
      if (!installIt) {
        prompt.error('PM2 is required for this target. Install it manually: bun add -g pm2');
        return 1;
      }
    }
    if (!(await installPm2(runner))) {
      prompt.error('Failed to install PM2.');
      return 1;
    }
    prompt.success('PM2 installed globally.');
  }

  // ---- 2. ecosystem.config.js --------------------------------------------
  if (ensureEcosystemConfig(cwd)) prompt.info('ecosystem.config.js created (defaults).');

  const snapshot = snapshotPackageJson(cwd);

  // ---- 3. packages --------------------------------------------------------
  if (opts.install) {
    if (outdated.length === 0) {
      prompt.success('Packages are up to date.');
    } else {
      prompt.write('\nUpdating packages...\n');
      const specs = outdated.map((entry) => `${entry.pkg}@latest`);
      let ok = runner('bun', ['add', ...specs], { cwd, inherit: true, timeoutMs: 600_000 }).ok;
      if (!ok) {
        ok = runner('npm', ['install', ...specs], { cwd, inherit: true, timeoutMs: 600_000 }).ok;
      }
      if (!ok) {
        prompt.error('Failed to update packages.');
        return 1;
      }
      prompt.success(`${outdated.length} package(s) updated.`);
    }
  } else if (outdated.length > 0) {
    prompt.info(`Run with --install to update ${outdated.length} package(s) first.`);
  }

  // ---- 4. migrations ------------------------------------------------------
  if (opts.migrate !== false) {
    const { command, args } = migrateInvocation();
    prompt.write('\nRunning migrations on the host...\n');
    const result = runner(command, args, { cwd, inherit: true, timeoutMs: 600_000 });
    if (!result.ok) {
      prompt.error('Migrations failed — deploy aborted.');
      return 1;
    }
    prompt.success('Migrations applied.');
  }

  // ---- 5. start or reload -------------------------------------------------
  prompt.write('\nStarting PM2 processes...\n');
  const reload = runner('pm2', ['startOrReload', 'ecosystem.config.js', '--update-env'], {
    cwd,
    inherit: true,
    timeoutMs: 60_000,
  });
  if (!reload.ok) {
    prompt.error('pm2 startOrReload failed.');
    return 1;
  }
  prompt.success('PM2 deploy done. Processes: okcms-api, okcms-admin, okcms-web, okcms-worker.');

  // ---- 6. history + docs --------------------------------------------------
  const pkg = await import('../package.json', { with: { type: 'json' } });
  const { addHistoryEntry } = await import('./history.js');
  addHistoryEntry(
    cwd,
    {
      mode: 'pm2',
      at: new Date().toISOString(),
      cliVersion: pkg.default.version,
      packages: outdated.map((entry) => ({ name: entry.name, from: entry.current, to: entry.latest })),
      message: `PM2 deploy — ${outdated.length} package(s) updated`,
      packageJsonSnapshot: snapshot,
    },
    pkg.default.version
  );

  const { updateProjectDocs } = await import('./docs-updater.js');
  const updated = updateProjectDocs(cwd);
  if (updated.length > 0) prompt.success(`Docs updated: ${updated.join(', ')}`);

  return 0;
}
